name: autoformat
on: pull_request
jobs:
  format:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          ref: ${{ github.head_ref }}
      - run: sudo apt install clang-format && bash ./scripts/format.sh
      - name: Check if anything changed
        id: git-check
        run: echo ::set-output name=modified::$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)
      - name: Push changes
        if: steps.git-check.outputs.modified == 'true'
        run: false
