name: cpplint
on: [push, pull_request]
jobs:
  cpplint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install cpplint
      - run: cpplint --recursive --filter=-legal/copyright --exclude=extern/ --exclude=build/ --quiet .
