name: gtest
on: [push, pull_request]
jobs:
  gtest:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - run: mkdir build && cd build && cmake .. && make && ./tests/tests
