name: gtest
on: pull_request
jobs:
  gtest:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - run: sudo apt install libx11-dev libxi-dev libgl1-mesa-dev libglu1-mesa-dev libxrandr-dev libxext-dev libxcursor-dev libxinerama-dev libxi-dev libglfw3-dev libglew-dev libglm-dev
      - run: mkdir build && cd build && cmake .. && make && ./tests/tests
